### ISSUE TITLE
libffm or libfm?

### ISSUE THREAD

**Issue by JoshuaC3** [CNevd/libffm-ftrl#1]
I am slightly confused. Is this a factorisation machine or a field-aware factorisation machine?

**Comment by CNevd** [comment]
it’s field-aware factorisation machine

**Comment by JoshuaC3** [comment]
I think I miss read the below text and the referenced paper.

"It can be 
[Factorization Machines with Follow-The-Regularized-Leader for CTR prediction in Display Advertising](http://www0.cs.ucl.ac.uk/staff/w.zhang/rtb-papers/fm-ftrl.pdf)
when we set all fields the same "

What you are saying is it can be the above FM when all fields are set the same. Is that correct?

**Comment by CNevd** [comment]
when num of fields is 1, it's FM :)

**Comment by JoshuaC3** [comment]
Excellent. I understand now. I misread this party because the hyperlink did not format like in my comment above. Here is print screen of what I see at `https://github.com/CNevd/libffm-ftrl`.

![github](https://cloud.githubusercontent.com/assets/11645712/18832682/d3584c96-83e4-11e6-931e-7c4a11d01064.png)

**Comment by CNevd** [comment]
ok sorry to confuse you, will correct it :)

**Comment by JoshuaC3** [comment]
Not at all! Thank you for an amazing and interesting rework of LIBFFM :)
