### ISSUE TITLE
features IDs

### ISSUE THREAD

**Issue by AMilkov** [CNevd/libffm-ftrl#2]
Is there a need the feature IDs to be unique or is it enough the combination of field + feature ID to be unique?

For example 
If we assume that field 1 is movie and field 2 is user and user A has ID 123 and movie B has ID 123  
is this a valid row:  
```
1:123:1 2:123:1
```

**Comment by CNevd** [comment]
@AMilkov the feature IDs are unique, so movie B's ID should not be 123

**Comment by AMilkov** [comment]
Thank you @CNevd !
