### ISSUE TITLE
AUC as optimization function

### ISSUE THREAD

**Issue by AMilkov** [CNevd/libffm-ftrl#3]
How hard is to add AUC as a optimization function?
Now the only option is logloss.

**Comment by CNevd** [comment]
you can mainly change the function `wTx` and `train` in `ffm.cpp` for computing auc loss and grad of each weight :)

**Comment by AMilkov** [comment]
@CNevd 

Mate, the reason behind my question is to understand if I can afford to hire you to implement that?  
I am afraid that I am not yet ready to do this all by myself ...

My Skype is **tonyboy17** - lets continue the conversation there.

**Comment by CNevd** [comment]
got it
