### ISSUE TITLE
which tools of ffm is better?

### ISSUE THREAD

**Issue by yangyiming1234** [CNevd/libffm-ftrl#5]
I found that there are several projects about ffm in your github, such as libffm-ftrl,Difacto_DMLC.Which one would you recommend to use? Do you have any data about their effectiveness and efficiency on benchmark dataset?

**Comment by CNevd** [comment]
libffm-ftrl is a single machine version with ftrl updater to produce sparse features
however, Difacto_DMLC is a distributed version with  Parameter Server of fm not ffm
